/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoardRouteImport } from './routes/board'
import { Route as BoardIndexRouteImport } from './routes/board.index'
import { Route as BoardIdRouteImport } from './routes/board.$id'
import { Route as NotesSlugRouteImport } from './routes/notes.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardIndexRoute = BoardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BoardRoute,
} as any)
const BoardIdRoute = BoardIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BoardRoute,
} as any)
const NotesSlugRoute = NotesSlugRouteImport.update({
  id: '/notes/$slug',
  path: '/notes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/board': typeof BoardRouteWithChildren
  '/board/$id': typeof BoardIdRoute
  '/notes/$slug': typeof NotesSlugRoute
  '/board/': typeof BoardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/board/$id': typeof BoardIdRoute
  '/notes/$slug': typeof NotesSlugRoute
  '/board': typeof BoardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/board': typeof BoardRouteWithChildren
  '/board/$id': typeof BoardIdRoute
  '/notes/$slug': typeof NotesSlugRoute
  '/board/': typeof BoardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/board' | '/board/$id' | '/notes/$slug' | '/board/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/board/$id' | '/notes/$slug' | '/board'
  id: '__root__' | '/' | '/board' | '/board/$id' | '/notes/$slug' | '/board/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardRoute: typeof BoardRouteWithChildren
  NotesSlugRoute: typeof NotesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/': {
      id: '/board/'
      path: '/'
      fullPath: '/board/'
      preLoaderRoute: typeof BoardIndexRouteImport
      parentRoute: typeof BoardRoute
    }
    '/board/$id': {
      id: '/board/$id'
      path: '/$id'
      fullPath: '/board/$id'
      preLoaderRoute: typeof BoardIdRouteImport
      parentRoute: typeof BoardRoute
    }
    '/notes/$slug': {
      id: '/notes/$slug'
      path: '/notes/$slug'
      fullPath: '/notes/$slug'
      preLoaderRoute: typeof NotesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BoardRouteChildren {
  BoardIdRoute: typeof BoardIdRoute
  BoardIndexRoute: typeof BoardIndexRoute
}

const BoardRouteChildren: BoardRouteChildren = {
  BoardIdRoute: BoardIdRoute,
  BoardIndexRoute: BoardIndexRoute,
}

const BoardRouteWithChildren = BoardRoute._addFileChildren(BoardRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardRoute: BoardRouteWithChildren,
  NotesSlugRoute: NotesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
